### ISSUE TITLE
Dependencies ignored by overrides

### ISSUE THREAD

**Issue by kennylavender** [paralleldrive/feature-toggles#11]
Dependencies are ignored by overrides, this could be a bug, but I would like some feedback to make sure overrides respecting dependencies is important.

Dependencies were respected by overrides in react-feature-toggles v1, seems to be an oversight in v2 changes.

Example of how `getCurrentActiveFeatures` ignores dependencies.
```js
const initialFeatures = [
  { name: 'foo', isActive: false }
  { name: 'bar', isActive: false, dependencies: [ 'foo' ] }
]

const req = { query: { ft: 'bar' } }
const activeFeatures = getCurrentActiveFeatures({ initialFeatures, req })
console.log(activeFeatures) // ['bar']
```
If `getCurrentActiveFeatures` was respecting dependencies when overriding `initalFeatures` then `'bar'` should not exist in `activeFeatures`

I am not too sure if this is a problem or not, but I am thinking it is because if we have features that depend on one another, then enabling a feature that depends on another feature that remains disabled could cause errors and other weirdness. I think overrides need to respect dependencies.

Thoughts?

**Comment by warrenv** [comment]
Add a dependency feature does cause complexity in this library. 
It could be omitted and left to the user to implement as best fits their situation.
