### ISSUE TITLE
Publish v1

### ISSUE THREAD

**Issue by kennylavender** [paralleldrive/feature-toggles#13]
Ready to publish 1.0.0

**Comment by kennylavender** [comment]
Hold off actually, I want to fix #11 and make some adjustments today.

**Comment by kennylavender** [comment]
@ericelliott after #24 #23 #22 get merged in we should be good to publish v1.

**Comment by ericelliott** [comment]
@paralleldrive/feature-toggles@1.0.0

🚀 🌝
