### ISSUE TITLE
Upgrade lodash dependency to version 4.17.11 or higher

### ISSUE THREAD

**Issue by LL782** [paralleldrive/feature-toggles#34]
Can you consider upgrading lodash to version 4.17.11 or higher

> Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS). It parses dates using regex strings, which may cause a slowdown of 2 seconds per 50k characters.

https://app.snyk.io/vuln/SNYK-JS-LODASH-73639

**Comment by ericelliott** [comment]
Absolutely. I'm currently working on the update for react-feature-toggles. If you want to make the PR for this repo, I'd be happy to merge and push a new release.

**Comment by ericelliott** [comment]
This issue is now fixed in [this PR](https://github.com/paralleldrive/feature-toggles/pull/35). Will merge shortly.

**Comment by ericelliott** [comment]
Published @paralleldrive/feature-toggles@1.0.4

**Comment by LL782** [comment]
Awesome! Impressive turn around 👍
